# Generated by Django 6.0.5 on 2026-05-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('cin', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agence', models.CharField(choices=[('Azilal', 'Azilal'), ('Afourer', 'Afourer'), ('Bzou', 'Bzou'), ('Demnate', 'Demnate'), ('Ait Attab', 'Ait Attab'), ('Tanante', 'Tanante'), ('Ouaouizeghth', 'Ouaouizeghth')], max_length=50)),
                ('type_probleme', models.CharField(choices=[('fuite', " Fuite d'eau"), ('pression', ' Basse pression'), ('coupure', " Coupure d'eau"), ('qualite', " Qualité de l'eau"), ('facturation', ' Facturation'), ('autre', ' Autre')], max_length=50)),
                ('urgence', models.CharField(choices=[('faible', ' Faible'), ('moyen', ' Modéré'), ('urgent', ' Urgent')], default='faible', max_length=10)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_cours', '🔧 En cours'), ('resolue', '✅ Cloturée')], default='en_attente', max_length=20)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('numero_contrat', models.CharField(blank=True, max_length=50, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
