# Generated by Django 6.0.5 on 2026-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='service',
            field=models.CharField(choices=[('eau', ' Eau'), ('electricite', ' Électricité'), ('assainissement', ' Assainissement')], default='eau', max_length=50),
        ),
    ]
